name: todo_open
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  intl: ^0.15.8
  material_search: ^0.2.8
  dio: ^2.1.3
  flutter_slidable: ^0.5.3
  image_picker: ^0.6.0+16
  file_picker: ^1.3.8
  firebase_auth: ^0.11.1+10
  google_sign_in: ^4.0.4
  firebase_core: ^0.4.0+6
  cloud_firestore: ^0.12.7
  firebase_database: ^3.0.4
  flutter_local_notifications: ^0.7.1+3
  path_provider: ^1.1.2
  scheduled_notifications: ^1.0.0
  location: ^2.3.5
  flutter_sound: ^1.4.2
  font_awesome_flutter: ^8.5.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/assets/icon/logo.png
    - lib/assets/icon/send.png
    - lib/assets/icon/blue.png
    - lib/assets/icon/orange.png
    - lib/assets/icon/green.png
    - lib/assets/icon/red.png
    - lib/assets/icon/purple.png
    - lib/assets/icon/graph.png
    - lib/assets/icon/suitcase.png
    - lib/assets/icon/cafe.png
    - lib/assets/icon/home.png
    - lib/assets/icon/user.png
    - lib/assets/icon/handshake.png

    - lib/assets/bg/image.png
    - lib/assets/bg/sidebar_bg.png
    - lib/assets/bg/bar.png

  fonts:
    - family: OpenSansSemiBold
      fonts:
        - asset: lib/assets/fonts/OpenSansSemiBold.ttf
          weight: 400

